//// filepath: online-cab-booking-service/user-service/src/main/resources/application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=Ankit@123
spring.jpa.hibernate.ddl-auto=update

server.port=8088